<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-19 at 22:14:34.
 */
class AccountControllerTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var AccountController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new AccountController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers AccountController::signupAction
     * @todo   Implement testSignupAction().
     */
    public function testSignupAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccountController::registerAction
     * @todo   Implement testRegisterAction().
     */
    public function testRegisterAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccountController::indexAction
     * @todo   Implement testIndexAction().
     */
    public function testIndexAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccountController::signinAction
     * @todo   Implement testSigninAction().
     */
    public function testSigninAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccountController::authenticateAction
     * @todo   Implement testAuthenticateAction().
     */
    public function testAuthenticateAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccountController::signoutAction
     * @todo   Implement testSignoutAction().
     */
    public function testSignoutAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
