<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-24 at 02:50:54.
 */
class AddressRepositoryTest extends PHPUnit_Extensions_Database_TestCase
{
    static private $pdo  = null;
    private        $conn = null;
    private        $obj;

    public function __construct()
    {

        $data_set = $this->createXMLDataSet(dirname(__FILE__) . '/../data/import.xml');

        $this->databaseTester = null;

        $this->getDatabaseTester()->setSetUpOperation($this->getSetUpOperation());
        $this->getDatabaseTester()->setDataSet($data_set);
        $this->getDatabaseTester()->onSetUp($data_set);

        $this->obj = new AddressRepository(self::$pdo);
    }

    /**
     * @return null|PHPUnit_Extensions_Database_DB_DefaultDatabaseConnection
     */
    final public function getConnection()
    {

        if ($this->conn === null) {
            if (self::$pdo == null) {
                self::$pdo = new PDO(
                  $GLOBALS['DB_DSN'],
                  $GLOBALS['DB_USER'],
                  $GLOBALS['DB_PASSWD']);
            }
            $this->conn
              = $this->createDefaultDBConnection(self::$pdo, $GLOBALS['DB_DBNAME']);
        }

        return $this->conn;
    }

    /**
     * @return PHPUnit_Extensions_Database_DataSet_ArrayDataSet
     */
    public function getDataSet()
    {
        $data = array();

        return $this->createArrayDataSet($data);
    }

    public function testAddress()
    {

        // temp
//        $this->assertEquals(2, $this->getConnection()->getRowCount('address'));
//        $this->assertTableRowCount("address", "2");

    }
}
